-------------------------------------------------
-------------------------- Miscellaneous
-------------------------------------------------
---@class creatureData
---@field objectID integer
---@field chasing af_services_player_player|false

---@class debounce
---@field duration number
---@field player af_services_player_player
---@field tag tag